export const myProjects = [
  {
    id: 7,
    title: "My Fin Pal",
    description: "A monthly expense managing AI that helps users track and optimize their spending habits.",
    subDescription: [
      "Developed an AI-powered expense tracker using React and Python.",
      "Implemented automated categorization of transactions for better financial insights.",
      "Designed a user-friendly dashboard with real-time spending analytics.",
      "Integrated secure data handling to ensure user privacy and financial security.",
    ],
    href: "",
    logo: "",
    image: "/assets/projects/my-fin-pal.jpg",
    tags: [
      {
        id: 1,
        name: "React",
        path: "/assets/logos/react.svg",
      },
      {
        id: 2,
        name: "Python",
        path: "/assets/logos/python.svg",
      },
      {
        id: 3,
        name: "AI",
        path: "/assets/logos/ai.svg",
      },
      {
        id: 4,
        name: "TailwindCSS",
        path: "/assets/logos/tailwindcss.svg",
      },
    ],
  },
  {
    id: 8,
    title: "Authentica",
    description: "An AI used to detect if an image is generated by AI or created by a human.",
    subDescription: [
      "Built a deep learning model to analyze and classify images as AI-generated or real.",
      "Developed a web interface for users to upload and verify image authenticity.",
      "Utilized Python and TensorFlow for model training and inference.",
      "Ensured high accuracy and low latency in detection results.",
    ],
    href: "",
    logo: "",
    image: "/assets/projects/authentica.jpg",
    tags: [
      {
        id: 1,
        name: "Python",
        path: "/assets/logos/python.svg",
      },
      {
        id: 2,
        name: "TensorFlow",
        path: "/assets/logos/tensorflow.svg",
      },
      {
        id: 3,
        name: "React",
        path: "/assets/logos/react.svg",
      },
      {
        id: 4,
        name: "TailwindCSS",
        path: "/assets/logos/tailwindcss.svg",
      },
    ],
  },
  {
    id: 9,
    title: "CrisisMaster",
    description: "A disaster preparedness learning web application.",
    subDescription: [
      "Created an interactive educational platform for disaster preparedness training.",
      "Implemented gamified learning modules to engage users and improve retention.",
      "Designed a responsive UI accessible on various devices for widespread reach.",
      "Integrated real-time quizzes and progress tracking for users.",
    ],
    href: "",
    logo: "",
    image: "/assets/projects/crisis-master.jpg",
    tags: [
      {
        id: 1,
        name: "React",
        path: "/assets/logos/react.svg",
      },
      {
        id: 2,
        name: "Node.js",
        path: "/assets/logos/nodejs.svg",
      },
      {
        id: 3,
        name: "Education",
        path: "/assets/logos/education.svg",
      },
      {
        id: 4,
        name: "TailwindCSS",
        path: "/assets/logos/tailwindcss.svg",
      },
    ],
  },
  {
    id: 10,
    title: "Blade of Vengeance",
    description: "A 2D action adventure and emotional game.",
    subDescription: [
      "Developed a 2D action-adventure game with a compelling emotional storyline.",
      "Designed intricate levels and character mechanics using Unity and C#.",
      "Implemented smooth combat systems and responsive controls.",
      "Optimized game performance for smooth gameplay on various platforms.",
    ],
    href: "",
    logo: "",
    image: "/assets/projects/blade-of-vengeance.jpg",
    tags: [
      {
        id: 1,
        name: "Unity",
        path: "/assets/logos/unity.svg",
      },
      {
        id: 2,
        name: "C#",
        path: "/assets/logos/csharp.svg",
      },
      {
        id: 3,
        name: "Game Dev",
        path: "/assets/logos/gamedev.svg",
      },
      {
        id: 4,
        name: "Pixel Art",
        path: "/assets/logos/pixelart.svg",
      },
    ],
  },
];

export const mySocials = [
  {
    name: "GitHub",
    href: "https://github.com/lingeswarandhanapal7-hub",
    icon: "/assets/socials/github.svg",
  },
  {
    name: "Linkedin",
    href: "https://www.linkedin.com/in/ali-sanati/",
    icon: "/assets/socials/linkedIn.svg",
  },
  {
    name: "Email",
    href: "mailto:lingeswarandhanapal7@gmail.com",
    icon: "/assets/socials/email.svg",
  },
];

export const experiences = [
  {
    title: "SSLC",
    job: "The Gugai Higher Secondary School, Salem",
    date: "2021-2022",
    contents: [
      "Completed SSLC with 82%.",
    ],
  },
  {
    title: "HSC",
    job: "The Gugai Higher Secondary School, Salem",
    date: "2023-2024",
    contents: [
      "Completed HSC with 80%.",
    ],
  },
  {
    title: "B.E Computer Science Engineering - 1st Year",
    job: "K.S.R College of Engineering",
    date: "2024-2025",
    contents: [
      "Completed 1st year with CGPA of 8.5.",
    ],
  },
  {
    title: "B.E Computer Science Engineering - 2nd Year",
    job: "K.S.R College of Engineering",
    date: "2025-2026",
    contents: [
      "Currently pursuing 2nd year B.E Computer Science Engineering.",
    ],
  },
];
export const reviews = [
  {
    name: "Jack",
    username: "@jack",
    body: "I've never seen anything like this before. It's amazing. I love it.",
    img: "https://robohash.org/jack",
  },
  {
    name: "Jill",
    username: "@jill",
    body: "I don't know what to say. I'm speechless. This is amazing.",
    img: "https://robohash.org/jill",
  },
  {
    name: "John",
    username: "@john",
    body: "I'm at a loss for words. This is amazing. I love it.",
    img: "https://robohash.org/john",
  },
  {
    name: "Alice",
    username: "@alice",
    body: "This is hands down the best thing I've experienced. Highly recommend!",
    img: "https://robohash.org/alice",
  },
  {
    name: "Bob",
    username: "@bob",
    body: "Incredible work! The attention to detail is phenomenal.",
    img: "https://robohash.org/bob",
  },
  {
    name: "Charlie",
    username: "@charlie",
    body: "This exceeded all my expectations. Absolutely stunning!",
    img: "https://robohash.org/charlie",
  },
  {
    name: "Dave",
    username: "@dave",
    body: "Simply breathtaking. The best decision I've made in a while.",
    img: "https://robohash.org/dave",
  },
  {
    name: "Eve",
    username: "@eve",
    body: "So glad I found this. It has changed the game for me.",
    img: "https://robohash.org/eve",
  },
];
